Update terraform-azure.yaml

diff --git a/.github/workflows/terraform-azure.yaml b/.github/workflows/terraform-azure.yaml
--- a/.github/workflows/terraform-azure.yaml
+++ b/.github/workflows/terraform-azure.yaml
@@ -175,7 +175,8 @@ jobs:
               echo "We are on the latest commit for main"
           else
               echo "We are behind on commits!"
-              (>&2 echo "Detected workflow running on out-of-date commit"; exit 1)
+              echo "::error::Detected workflow running on out-of-date commit"
+              exit 1
           fi
 
       - name: Terraform Apply
